spring:
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://${SERVER_IP}:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
springdoc:
  api-docs:
    path: /api-docs
name: dev-yaml
server:
  port: 6969
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:54321/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
name: test-yaml
